In [6]:
import numpy as np

In [7]:
my_list=["ram",123,50.5,7+2j]
print(my_list)
type(my_list)

['ram', 123, 50.5, (7+2j)]


list

In [8]:
l1=["sarthak",1,2,True]
print(l1)
type(l1)

['sarthak', 1, 2, True]


list

### Create array

In [9]:
a=np.array([1,2,3,6,9])
print(a)
type(a)#int

[1 2 3 6 9]


numpy.ndarray

In [10]:
my_array=np.array(["ram",123,50.5,7+2j])
print(my_array)
type(my_array)#string>complex>float>int

['ram' '123' '50.5' '(7+2j)']


numpy.ndarray

In [11]:
my_array=np.array([123,50.5,7+2j])
print(my_array)
type(my_array)#complex>float>int

[123. +0.j  50.5+0.j   7. +2.j]


numpy.ndarray

In [12]:
x=np.array([123,"sarthak","chetana",45.7])
print(x)
type(x)#String>float>int

['123' 'sarthak' 'chetana' '45.7']


numpy.ndarray

In [13]:
x=np.array([123,2+4j,45.7,2])
print(x)
type(x)#Complex>float>int

[123. +0.j   2. +4.j  45.7+0.j   2. +0.j]


numpy.ndarray

### numpy priority String>Complex>Float>Int

In [14]:
my_array=np.array([123,50.5])
print(my_array)
type(my_array)#Float>Int

[123.   50.5]


numpy.ndarray

### Empty Numpy array

In [15]:
a=np.array([])
a

array([], dtype=float64)

### Attributes of Numpy

### 1.ndim

In [16]:
x=np.array([[123,"sarthak","chetana",45.7],[1,2,3,4]])
print(x)

[['123' 'sarthak' 'chetana' '45.7']
 ['1' '2' '3' '4']]


In [17]:
x.ndim

2

In [18]:
x=np.array([[123,45,45,60],[1,2,3,4],[10,20,30,40]])
print(x)

[[123  45  45  60]
 [  1   2   3   4]
 [ 10  20  30  40]]


In [19]:
x.ndim

2

### 2.shape

In [20]:
x.shape

(3, 4)

### 3.size

In [21]:
x.size

12

### 4.dtype

In [22]:
x.dtype

dtype('int32')

### 5.itemsize

In [23]:
x.itemsize

4

In [24]:
x.data

### Array Creation Function

### 1.np.array()

In [25]:
a_list=np.array([["a","b","c","d"],["w","x","y","z"]])
print(a_list)

[['a' 'b' 'c' 'd']
 ['w' 'x' 'y' 'z']]


In [26]:
b_tuple=np.array([("a","b","c","d"),("w","x","y","z")])
print(b_tuple)

[['a' 'b' 'c' 'd']
 ['w' 'x' 'y' 'z']]


In [28]:
b_tuple.shape

(2, 4)

### 2.np.zeros()

In [29]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 3.zeros_like()

In [93]:
a_list1=np.array([[1,2,3,6],[4,8,7,9],[4,8,9,7]])
print(a_list1)

[[1 2 3 6]
 [4 8 7 9]
 [4 8 9 7]]


In [94]:
a_list1.ndim

2

In [95]:
np.zeros_like(a_list1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 4.ones()

In [96]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### 5.ones_like

In [97]:
y=np.array([[1,2,3,4],[5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [98]:
np.ones_like(y)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### 6.np.empty()

In [99]:
np.empty(0)

array([], dtype=float64)

### 7.np.arrange()

In [100]:
for i in range(1,19,3):   #range
    print(i)

1
4
7
10
13
16


In [101]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

### 8.np.linespace()

In [102]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

### 9.np.logspace()

In [103]:
np.logspace(1,20,10)

array([1.00000000e+01, 1.29154967e+03, 1.66810054e+05, 2.15443469e+07,
       2.78255940e+09, 3.59381366e+11, 4.64158883e+13, 5.99484250e+15,
       7.74263683e+17, 1.00000000e+20])

### 1.reshape()

In [104]:
a_list=np.array([[1,2,3,4],[4,8,7,9],[4,8,9,7]])
a_list #12=(2,6),(3,4),(12,1)

array([[1, 2, 3, 4],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [105]:
a_list.reshape(6,2)

array([[1, 2],
       [3, 4],
       [4, 8],
       [7, 9],
       [4, 8],
       [9, 7]])

In [106]:
a_list.shape

(3, 4)

### 2.Transpose()

In [107]:
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
y.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 3.Concatenate()

In [109]:
np.concatenate(a_list)

array([1, 2, 3, 4, 4, 8, 7, 9, 4, 8, 9, 7])

In [110]:
np.concatenate(y)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 4.vstack()

In [111]:
np.vstack(y)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [112]:
np.vstack(a_list)

array([[1, 2, 3, 4],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

### 5.hstack()

In [113]:
np.hstack(a_list)

array([1, 2, 3, 4, 4, 8, 7, 9, 4, 8, 9, 7])

In [114]:
np.hstack(y)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 6.split()

In [115]:
a_list

array([[1, 2, 3, 4],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [116]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
np.split(e,(5))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

### 7.delete()

In [118]:
np.delete(e,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

### 8.insert()

In [119]:
np.insert(e,5,1)

array([0, 1, 2, 3, 4, 1, 5, 6, 7, 8, 9])

### 9.append()

In [120]:
np.append(e,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

### Mathematical Functions:

### 1.numpy.add

In [121]:
a_list1

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [122]:
b_list1=np.array([[10,20,30,40],[50,30,20,10],[60,70,40,30]])
b_list1

array([[10, 20, 30, 40],
       [50, 30, 20, 10],
       [60, 70, 40, 30]])

In [123]:
np.add(a_list1,b_list1)

array([[11, 22, 33, 46],
       [54, 38, 27, 19],
       [64, 78, 49, 37]])

In [124]:
b_list1+a_list1

array([[11, 22, 33, 46],
       [54, 38, 27, 19],
       [64, 78, 49, 37]])

### 2.numpy.subtract

In [125]:
np.subtract(a_list1,b_list1)

array([[ -9, -18, -27, -34],
       [-46, -22, -13,  -1],
       [-56, -62, -31, -23]])

In [126]:
b_list1-a_list1

array([[ 9, 18, 27, 34],
       [46, 22, 13,  1],
       [56, 62, 31, 23]])

### 3.numpy.multiply

In [127]:
np.multiply(a_list1,b_list1)

array([[ 10,  40,  90, 240],
       [200, 240, 140,  90],
       [240, 560, 360, 210]])

In [128]:
b_list1*a_list1

array([[ 10,  40,  90, 240],
       [200, 240, 140,  90],
       [240, 560, 360, 210]])

### 4.numpy.divide

In [163]:
np.divide(a_list1,b_list1)

array([[0.1       , 0.1       , 0.1       , 0.15      ],
       [0.08      , 0.26666667, 0.35      , 0.9       ],
       [0.06666667, 0.11428571, 0.225     , 0.23333333]])

In [165]:
a_list1/b_list1

array([[0.1       , 0.1       , 0.1       , 0.15      ],
       [0.08      , 0.26666667, 0.35      , 0.9       ],
       [0.06666667, 0.11428571, 0.225     , 0.23333333]])

### 5.numpy.power

In [131]:
np.power(a_list1,b_list1)

array([[          1,     1048576, -1010140999,           0],
       [          0,           0, -1199696159,  -808182895],
       [          0,           0, -1669737407,  1878557649]])

In [132]:
b_list1**a_list1

array([[         10,         400,       27000,  -198967296],
       [    6250000, -1029996288,  1280000000,  1000000000],
       [   12960000,   999596288,   671088640,   395163520]])

In [133]:
a_list1

array([[1, 2, 3, 6],
       [4, 8, 7, 9],
       [4, 8, 9, 7]])

In [134]:
b_list1

array([[10, 20, 30, 40],
       [50, 30, 20, 10],
       [60, 70, 40, 30]])

In [135]:
20**2

400

### 6.numpy.sqrt

In [137]:
np.sqrt(a_list1)

array([[1.        , 1.41421356, 1.73205081, 2.44948974],
       [2.        , 2.82842712, 2.64575131, 3.        ],
       [2.        , 2.82842712, 3.        , 2.64575131]])

In [138]:
np.sqrt(b_list1)

array([[3.16227766, 4.47213595, 5.47722558, 6.32455532],
       [7.07106781, 5.47722558, 4.47213595, 3.16227766],
       [7.74596669, 8.36660027, 6.32455532, 5.47722558]])

In [139]:
a_list1**2

array([[ 1,  4,  9, 36],
       [16, 64, 49, 81],
       [16, 64, 81, 49]])

In [140]:
b_list1**2

array([[ 100,  400,  900, 1600],
       [2500,  900,  400,  100],
       [3600, 4900, 1600,  900]])

### 7.numpy.sum()

In [141]:
a_list1.sum()

68

In [142]:
b_list1.sum()

410

### 8.numpy.mean()

In [143]:
a_list1.mean()

5.666666666666667

In [144]:
b_list1.mean()

34.166666666666664

### 9.numpy.median()

In [148]:
np.median(a_list1)

6.5

In [149]:
np.median(b_list1)

30.0

### 10.numpy.min()

In [150]:
np.min(a_list1)

1

In [151]:
np.max(b_list1)

70

### indexing and slicing

#### indexing of 2D array

In [152]:
a=np.array([[5,2,14],[1,2,3]])
a.ndim

2

In [153]:
a[0][1]

2

In [154]:
a[1][0]

1

In [155]:
arr1=np.array([[[10,11,12],[13,14,15],[16,17,18]],
               [[20,21,21],[23,24,25],[26,27,28]],
               [[30,31,32],[33,34,35],[36,37,38]]])

In [159]:
arr1[0][1][2]

15

In [157]:
arr1[2][1][0]

33

#### Indexing of 3D array

### Creating Randome numbers

In [160]:
np.random.rand(4)

array([0.34617133, 0.5175489 , 0.0719339 , 0.43054306])

In [161]:
np.random.rand(4,4)

array([[0.13297846, 0.35153733, 0.39966701, 0.16075876],
       [0.16818011, 0.45782141, 0.51282256, 0.01080493],
       [0.844712  , 0.11523181, 0.70756792, 0.21216528],
       [0.1258657 , 0.18353267, 0.96602028, 0.50987457]])

In [162]:
a=np.random.rand(4,4,4)
print(a)
a.ndim

[[[0.22176652 0.97696879 0.31394319 0.86862682]
  [0.67774422 0.70422155 0.77966369 0.54766178]
  [0.56926227 0.98734089 0.59439577 0.78790055]
  [0.75108371 0.34149135 0.28200704 0.45100922]]

 [[0.09789567 0.89603258 0.05587389 0.4481528 ]
  [0.46442641 0.37460523 0.4377784  0.02161683]
  [0.103496   0.70457875 0.22018674 0.41460617]
  [0.71041679 0.60085249 0.39396077 0.48968806]]

 [[0.43093052 0.20233792 0.18183967 0.54283559]
  [0.06603678 0.23554555 0.47742213 0.10836226]
  [0.51128759 0.86695091 0.58672695 0.01457804]
  [0.86340519 0.35840992 0.87664    0.73624671]]

 [[0.07019462 0.45176842 0.64883625 0.26194209]
  [0.83097058 0.61518612 0.68004986 0.9195129 ]
  [0.11550893 0.12788051 0.19260375 0.60616915]
  [0.26201902 0.39718182 0.98254713 0.00872003]]]


3